#!/bin/sh
if [ -n "$PUSH_REMOTE" ]; then
	if [ "$VCS" = git ] && [ -d .git ]; then
		for REMOTE in $PUSH_REMOTE; do
			git push -q "$REMOTE" master || true
		done
	elif [ "$VCS" = hg ] && [ -d .hg ]; then
		for REMOTE in $PUSH_REMOTE; do
			hg push -q "$REMOTE" || true
		done
	else
		echo "PUSH_REMOTE not yet supported for $VCS" >&2
	fi
fi
